### ISSUE TITLE
Error occurs when running 'make'

### ISSUE THREAD

**Issue by fpigerre** [gitchain/gitchain#10]
When running `make`, after running `make prepare`, I received the following error:
https://gist.github.com/psgs/3f3964287513128f5572

My $GOROOT and $GOPATH have been set and the `make prepare` command seemed to have worked without errors. When viewing my $GOPATH directory however, I seem to be unable to find any files other than a folder named 'wendy', under `\GoPath\src\github.com\gitchain`. Is this normal?

I'm currently running Windows 7 with Go 1.2.2.

Thanks,
psgs

**Comment by lionzeye** [comment]
This seems to be a related issue: https://github.com/gitchain/gitchain/issues/9

**Comment by fpigerre** [comment]
Yes, It is. The issue's now been fixed.
Thanks @lionzeye :+1:
