### ISSUE TITLE
Mining and economics

### ISSUE THREAD

**Issue by KOLANICH** [gitchain/gitchain#21]
1 what will make miners to mine?
2 may be it is better to implement it on top some data-oriented "coin", such as datacoin?

**Comment by yrashk** [comment]
I suggest to post this kind of questions to the mailing list https://groups.google.com/group/gitchain

Lets use github issues for development related matters.

**Comment by yrashk** [comment]
Also, there's a development survey wiki page
https://github.com/gitchain/gitchain/wiki/Development-Survey for some
specific notes to be edited collaboratively.
