### ISSUE TITLE
Git coin?

### ISSUE THREAD

**Issue by eduzol** [gitchain/gitchain#36]
Hi, I am interested in this project, is it still alive?
Please let me (us?) know if you need help

**Comment by gdvine** [comment]
What is Git Coin? Gitchain hasn't been worked on in a while, but I still think it is a very valuable project that deserves to be worked on...

**Comment by ghost** [comment]
@eduzol would you mind closing this issue as a duplicate of #29 and partial duplicate of #34?

**Comment by eduzol** [comment]
thanks, think there is an huge opportunity to create something like a `github open source crypto token` something like steemit for open source development. I would be interested in working on such project (in case someone is reading this thread). Closing
