### ISSUE TITLE
go-bindata install link wrong

### ISSUE THREAD

**Issue by Licenser** [gitchain/gitchain#4]
the makefile executes:

```
go get github.com/jteeuwen/go-bindata
```

this does however not install to go-bindata executable making the following steps fail

This code installs the tool:

```
go get github.com/jteeuwen/go-bindata/go-bindata
```

**Comment by yrashk** [comment]
Thanks! Fixed in eab3def3432efe57eff8bb2903d2ffc5c8a92791
