### ISSUE TITLE
`make` fails, after running `make prepare`

### ISSUE THREAD

**Issue by zackp30** [gitchain/gitchain#9]
```
main.go:14:2: cannot find package "github.com/gitchain/gitchain/server" in any of:
        /home/morpheus/go/src/pkg/github.com/gitchain/gitchain/server (from $GOROOT)
        /home/morpheus/gostuff/src/github.com/gitchain/gitchain/server (from $GOPATH)
main.go:15:2: cannot find package "github.com/gitchain/gitchain/server/api" in any of:
        /home/morpheus/go/src/pkg/github.com/gitchain/gitchain/server/api (from $GOROOT)
        /home/morpheus/gostuff/src/github.com/gitchain/gitchain/server/api (from $GOPATH)
make: *** [gitchain] Error 1
```

**Comment by yrashk** [comment]
Where did you clone gitchain into?

**Comment by zackp30** [comment]
`$HOME`

You're doing a good job on this by the way, can't wait to see it finished. :smile:

**Comment by yrashk** [comment]
Thanks! Move it to $GOPATH/src/github.com/gitchain (mkdir -p $GOPATH/src/github.com/gitchain beforehand) so that you have $GOPATH/src/github.com/gitchain/gitchain. Go in there and try running make.

**Comment by zackp30** [comment]
Aha, thanks!
Have a nice day! :smile:

**Comment by nicola** [comment]
OK I got it to work. It should be more documented that we have to `make` inside the `$GOPATH`
